language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.1

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-android-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_script:
    - ./gradlew test
    - ./gradlew connectedAndroidTest
